name: Add issues to project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/CQCL-DEV/projects/19
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
        id: add-project
      - uses: titoportas/update-project-fields@v0.1.0
        with:
          project-url: https://github.com/orgs/CQCL-DEV/projects/19
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          item-id: ${{ steps.add-project.outputs.itemId }}
          field-keys: Epic
          field-values: Qermit