name: Release
on:
  workflow_dispatch: {}
  # Runs when a version tag is pushed
  push:
    tags:
      - v**

# Safeguard to avoid having multiple deployments running concurrently
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  Release:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
  
    steps:

      - name: Checkout Qermit
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Poetry
        uses: snok/install-poetry@v1
      
      - name: Build Qermit
        run: poetry build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Publish Qermit
        run: poetry publish -u __token__ -p ${{ secrets.PYPI_RELEASE_TOKEN }} --build